services:
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    image: api:v1
    container_name: api
    depends_on:
      - database
    env_file:
      - .env
    restart: on-failure
  
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    ports: 
      - 1883:1883
    image: broker:v1
    container_name: broker
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    image: database:v1
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    image: ingestor:v1
    container_name: ingestor
    depends_on:
      - broker
      - database
    restart: on-failure
    env_file:
      - .env
